using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using System.Linq;
using System.Text;
using System.Threading;

namespace HunterPie.UI.Architecture.Views.Generators;

#nullable enable
[Generator]
internal class ViewModelPropertyGenerator : IIncrementalGenerator
{
    private record struct ViewDetails(
        string Namespace,
        string ClassName,
        string ViewModelType
    );

    private record struct Result(
        ViewDetails? Details = null,
        Diagnostic? Diagnostic = null
    );

    private static readonly DiagnosticDescriptor ClassMustBePartialRule = new(
        id: "HP1000",
        title: "View class must be partial",
        messageFormat: "The class '{0}' is decorated with [View] but is not marked as partial",
        category: "Design",
        defaultSeverity: DiagnosticSeverity.Error, // Can be Error, Warning, Info, or Hidden
        isEnabledByDefault: true
    );

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        IncrementalValuesProvider<Result?> provider = context.SyntaxProvider.ForAttributeWithMetadataName(
            fullyQualifiedMetadataName: "HunterPie.UI.Architecture.Views.ViewAttribute`1",
            predicate: static (syntaxNode, _) => syntaxNode is ClassDeclarationSyntax,
            transform: GetViewDetails
        ).Where(it => it is not null);

        context.RegisterSourceOutput(provider, static (ctx, result) =>
        {
            if (!result.HasValue)
                return;

            if (result.Value.Diagnostic is { } diag)
                ctx.ReportDiagnostic(diag);

            if (result.Value.Details is { } details)
                GenerateSource(ctx, details);
        });
    }

    private static Result? GetViewDetails(GeneratorAttributeSyntaxContext ctx, CancellationToken _)
    {
        var classDecl = (ClassDeclarationSyntax)ctx.TargetNode;
        var classSymbol = (INamedTypeSymbol)ctx.TargetSymbol;

        bool isPartial = classDecl.Modifiers.Any(SyntaxKind.PartialKeyword);
        if (!isPartial)
        {
            return new Result(
                Diagnostic: Diagnostic.Create(
                    descriptor: ClassMustBePartialRule,
                    location: classDecl.Identifier.GetLocation(),
                    messageArgs: classSymbol.Name
                )
            );
        }

        AttributeData? attribute = ctx.Attributes.FirstOrDefault();

        if (attribute?.AttributeClass?.TypeArguments.FirstOrDefault() is not INamedTypeSymbol viewModelTypeArg)
            return null;

        return new Result(
            Details: new ViewDetails(
                Namespace: classSymbol.ContainingNamespace.ToDisplayString(),
                ClassName: classSymbol.Name,
                ViewModelType: viewModelTypeArg.ToDisplayString()
            )
        );
    }

    private static void GenerateSource(SourceProductionContext context, ViewDetails details)
    {
        string ns = string.IsNullOrEmpty(details.Namespace)
            ? string.Empty
            : $"namespace {details.Namespace}";

        string source = $$"""
            // <auto-generated/>
            {{ns}};

            partial class {{details.ClassName}}
            {
                /// <summary>
                /// Strongly-typed access to UI component's DataContext
                /// </summary>
                private {{details.ViewModelType}} ViewModel => ({{details.ViewModelType}})(DataContext);
            }
            """;

        context.AddSource(
            hintName: $"{details.ClassName}.ViewModel.g.cs",
            sourceText: SourceText.From(source, encoding: Encoding.UTF8)
        );
    }
}