<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Authors>Haato</Authors>
        <Company>HunterPie</Company>
        <PackageId>HunterPie.Integrations</PackageId>
        <Description>HunterPie game integrations that provides the concrete implementation of game integrations</Description>
        <PackageTags>hunterpie;core;plugins</PackageTags>
        <RepositoryUrl>https://github.com/HunterPie/HunterPie</RepositoryUrl>
        <PackageLicenseExpression>Apache-2.0</PackageLicenseExpression>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <AssemblyVersion>2.15.0.163</AssemblyVersion>
        <FileVersion>2.15.0.163</FileVersion>
        <Version>2.15.0.158</Version>
        <LangVersion>14.0</LangVersion>
    </PropertyGroup>
    <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
        <ShouldCreateLogs>True</ShouldCreateLogs>
        <AdvancedSettingsExpanded>True</AdvancedSettingsExpanded>
        <UpdateAssemblyVersion>False</UpdateAssemblyVersion>
        <UpdateAssemblyFileVersion>False</UpdateAssemblyFileVersion>
        <UpdateAssemblyInfoVersion>False</UpdateAssemblyInfoVersion>
        <UpdatePackageVersion>False</UpdatePackageVersion>
        <AssemblyInfoVersionType>SettingsVersion</AssemblyInfoVersionType>
        <InheritWinAppVersionFrom>None</InheritWinAppVersionFrom>
    </PropertyGroup>
    <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
        <ShouldCreateLogs>True</ShouldCreateLogs>
        <AdvancedSettingsExpanded>True</AdvancedSettingsExpanded>
        <UpdateAssemblyVersion>False</UpdateAssemblyVersion>
        <UpdateAssemblyFileVersion>False</UpdateAssemblyFileVersion>
        <UpdateAssemblyInfoVersion>False</UpdateAssemblyInfoVersion>
        <UpdatePackageVersion>False</UpdatePackageVersion>
        <AssemblyInfoVersionType>SettingsVersion</AssemblyInfoVersionType>
        <InheritWinAppVersionFrom>None</InheritWinAppVersionFrom>
    </PropertyGroup>
    <ItemGroup>
        <ProjectReference Include="..\HunterPie.Core\HunterPie.Core.csproj" />
    </ItemGroup>
    <ItemGroup>
        <Folder Include="Datasources\MonsterHunterRise\Definitions\World\" />
        <Folder Include="Datasources\MonsterHunterRise\Entity\Game\Quest\" />
        <Folder Include="Datasources\MonsterHunterWilds\Entity\Activities\Data\" />
        <Folder Include="Datasources\MonsterHunterWilds\Entity\Game\Moon\" />
        <Folder Include="Datasources\MonsterHunterWilds\Entity\Game\Quest\Data\" />
        <Folder Include="Datasources\MonsterHunterWilds\Utils\" />
        <Folder Include="Datasources\MonsterHunterWorld\Process\" />
    </ItemGroup>
</Project>