<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Authors>Haato</Authors>
        <Company>HunterPie</Company>
        <PackageId>HunterPie.Platforms</PackageId>
        <Description>HunterPie OS integrations and utilities</Description>
        <PackageTags>hunterpie;system;plugins</PackageTags>
        <RepositoryUrl>https://github.com/HunterPie/HunterPie</RepositoryUrl>
        <PackageLicenseExpression>Apache-2.0</PackageLicenseExpression>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <LangVersion>14.0</LangVersion>
        <AssemblyVersion>1.3.0.107</AssemblyVersion>
        <FileVersion>1.3.0.107</FileVersion>
        <Version>1.3.0.106</Version>
    </PropertyGroup>
    <ItemGroup>
        <ProjectReference Include="..\HunterPie.Core\HunterPie.Core.csproj" />
        <ProjectReference Include="..\HunterPie.DI\HunterPie.DI.csproj" />
    </ItemGroup>
    <ItemGroup>
        <Folder Include="Common\Logging\" />
        <Folder Include="Windows\Memory\" />
    </ItemGroup>
</Project>