namespace HunterPie.Integrations.Datasources.MonsterHunterRise.Entity.Enums;

[Flags]
public enum CommonConditions : ulong
{
    None = 0,
    ABN_ATTACK_UP = 1,
    ABN_DEFENSE_UP = 1 << 1,
    StaminaUp = 1 << 2,
    ABN_IMMUNITY = 1 << 3,
    ABN_AFFINITY_UP = 1 << 4,
    ABN_KNOCKBACK_NEG = 1 << 5,
    ElementAttackUp = 1 << 6,
    Stamina = 1 << 7,
    ABN_HEALTH_REGEN = 1 << 8,
    ABN_GOURMET_FISH = 1 << 9,
    ABN_SONIC_BARRIER = 1 << 10,
    ABN_DIVINE_PROTECTION = 1 << 11,
    ABN_EARPLUG = 1 << 12,
    EscapeUp = 1 << 13,
    ABN_NATURAL_HEALING = 1 << 14,
    AttackUpEffectOnly = 1 << 15,
    Reverse16 = 1 << 16,
    Reverse17 = 1 << 17,
    Reverse18 = 1 << 18,
    Reverse19 = 1 << 19,
    Reverse20 = 1 << 20,
    Reverse21 = 1 << 21,
    Reverse22 = 1 << 22,
    Reverse23 = 1 << 23,
    Reverse24 = 1 << 24,
    Reverse25 = 1 << 25,
    ABN_HEROICS = 1 << 26,
    ABN_PEAK_PERFORMANCE = 1 << 27,
    ABN_DRAGONHEART = 1 << 28,
    ABN_LATENTPOWER = 1 << 29,
    ABN_AGITATOR = 1 << 30,
    ABN_OFFENSIVE_GUARD = 1UL << 31,
    ABN_DEFIANCE = 1UL << 32,
    ABN_GRINDER_S = 1UL << 33,
    ABN_RUBY_WIREBUG = 1UL << 34,
    ABN_GOLD_WIREBUG = 1UL << 36,
    Redirection = 1UL << 40,
    SymbiosisLevel1 = 1UL << 41,
    SymbiosisLevel2 = 1UL << 42,
    SymbiosisLevel3 = 1UL << 43,
    FuriousHalf = 1UL << 44,
    FuriousFull = 1UL << 45,
    ABN_DANGO_DEFENDER = 1UL << 46,
    DebuffAttackUp = 1UL << 47,
    ABN_EARPLUG_PLUS = 1UL << 48,
    ABN_TREMORS_NEG = 1UL << 49,
    ABN_WIND_PRESSURE = 1UL << 50,
    VirusOvercomeCriticalUp = 1UL << 51,
    BloodySkillHeal = 1UL << 52,
    FuriousStaminaBuff = 1UL << 53,
    InterpidHeart = 1UL << 54,
    WireStopRegene = 1UL << 55,
    VirusOvercomeIcon = 1UL << 56,
    ABN_WINDMANTLE = 1UL << 57,
    BerserkRed = 1UL << 58,
    BerserkBlue = 1UL << 59,
    StrifeSmall = 1UL << 60,
    StrifeLarge = 1UL << 61,
    PowderMantle = 1UL << 62
}