namespace HunterPie.Integrations.Datasources.MonsterHunterRise.Entity.Enums;

[Flags]
public enum DebuffConditions : ulong
{
    None = 0,
    NoData1 = 1,
    ABN_FIRE = 1 << 1,
    NoData2 = 1 << 2,
    ABN_WATER = 1 << 3,
    NoData3 = 1 << 4,
    ABN_THUNDER = 1 << 5,
    NoData4 = 1 << 6,
    ABN_ICE = 1 << 7,
    NoData5 = 1 << 8,
    DragonL = 1 << 9,
    ABN_RES_DOWN_S = 1 << 10,
    ABN_RES_DOWN_L = 1 << 11,
    VitalDamaging = 1 << 12,
    ABN_BUBBLES = 1 << 13,
    RedBubble = 1 << 14,
    GreenBubble = 1 << 15,
    ABN_FRENZY_BUILDUP = 1 << 16,
    VirusOnsetNearness = 1 << 17,
    VirusOvercomeNearness = 1 << 18,
    ABN_FRENZY = 1 << 19,
    ABN_FRENZY_IMMUNITY = 1 << 20,
    Territory = 1 << 21,
    ABN_HELLFIRE1 = 1 << 22,
    ABN_HELLFIRE2 = 1 << 23,
    Bomb1 = 1 << 24,
    Bomb2 = 1 << 25,
    Bomb3 = 1 << 26,
    GoldMudSlip = 1 << 27,
    MagmaSlip = 1 << 28,
    EnemyFireSlip = 1 << 29,
    NoData6 = 1 << 30,
    NoData7 = 1UL << 31,
    ABN_POISON = 1UL << 32,
    ABN_NOXIOUS_POISON = 1UL << 33,
    ABN_DEADLY_POISON = 1UL << 34,
    ABN_SLEEP = 1UL << 35,
    ABN_PARALYSIS = 1UL << 36,
    ABN_STUN = 1UL << 37,
    ABN_STENCH = 1UL << 38,
    LeadEnemy = 1UL << 39,
    LeadEnemyAfter = 1UL << 40,
    ABN_BUBBLES_PLUS = 1UL << 41,
    RedBubbleDaruma = 1UL << 42,
    GreenBubbleDaruma = 1UL << 43,
    ABN_LEECHED = 1UL << 44,
    ABN_BLEED = 1UL << 45,
    Confusion = 1UL << 46,
    ABN_DEF_DOWN_S = 1UL << 47,
    ABN_DEF_DOWN_L = 1UL << 48,
    ABN_WEBBED = 1UL << 49,
    VirusLatencyMiddle = 1UL << 51,
    ABN_BLOOD = 1UL << 52,
    MysteryDebuffHeal = 1UL << 53
}