name: cd/release

on:
  push:
    # branches:
    #   - main

defaults:
  run:
    shell: pwsh

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: setup-msbuild
        uses: microsoft/setup-msbuild@v3
        with:
          vs-version: 18.8.2

      - name: setup-python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: restore-dependencies
        run: |
          msbuild -m /t:Restore
          pip install -r ./Scripts/release/requirements.txt

      - name: build-project
        run: |
          msbuild /p:Configuration=Release /p:Platform=x64 /v:q /nologo
      
      - name: package-release
        run: |
          python ./Scripts/release/package.py ./HunterPie/bin/Release/net10.0-windows7.0
          
      - name: Deploy
        uses: BetaHuhn/do-spaces-action@v2.0.105
        with:
          access_key: ${{ secrets.AWS_ACCESS_KEY }}
          secret_key: ${{ secrets.AWS_SECRET_KEY }}
          space_name: ${{ vars.BUCKET_NAME }} 
          space_region: ${{ vars.BUCKET_REGION }}
          source: bin/deploy
          out_dir: qa/releases